name: cgan-sae_env
channels:
  - pytorch
  - conda-forge    
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy>=1.19
  - pandas>=1.3
  - scikit-learn>=1.0
  - matplotlib>=3.5
  - jupyter          
  - pip:
    - torch==2.1.0